name       : amsynth
version    : 1.7.0
release    : 1
source     :
    - https://github.com/amsynth/amsynth/archive/release-1.7.0.tar.gz : 176bfc8bc7eee60e6826572c8f9e9ce555c11687b063c5fb904836c44b4616b5
license    : GPL-2.0
component  : multimedia.audio
summary    : amsynth is an analog modelling software synthesizer.
description: |
    amsynth is an analog modelling (a.k.a virtual analog) software synthesizer.

    It mimics the operation of early analog subtractive synthesizers with classic oscillator waveforms, envelopes, filter, modulation and effects.

    The aim is to make it easy to create and modify sounds.
builddeps  :
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(alsa)
    - pkgconfig(jack)
    - pkgconfig(lash-1.0)
    - pkgconfig(sndfile)
    - pkgconfig(liblo)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(atkmm-1.6)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
