name       : amsynth
version    : 1.10.0
release    : 11
source     :
    - https://github.com/amsynth/amsynth/releases/download/release-1.10.0/amsynth-1.10.0.tar.gz : c662232c7a8e87fd907e493bf4660dba4e05a4ad4c3c5380212f056d8dc03826
license    : GPL-2.0-only
component  : multimedia.audio
summary    : amsynth is an analog modelling software synthesizer.
description: |
    amsynth is an analog modelling (a.k.a virtual analog) software synthesizer. It mimics the operation of early analog subtractive synthesizers with classic oscillator waveforms, envelopes, filter, modulation and effects. The aim is to make it easy to create and modify sounds.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(liblo)
    - pkgconfig(sndfile)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
