name       : amsynth
version    : 1.13.2
release    : 17
source     :
    - https://github.com/amsynth/amsynth/releases/download/release-1.13.2/amsynth-1.13.2.tar.gz : 1f46a9bd58e0cb966ec750d4c0633f29be7a4b8ed36737194050e59e423aa34f
homepage   : https://amsynth.github.io/
license    : GPL-2.0-only
component  : multimedia.audio
summary    : Analog modelling software synthesizer which works standalone and as a VST/LV2 plugin
description: |
    amsynth is an analog modelling (a.k.a virtual analog) software synthesizer. It mimics the operation of early analog subtractive synthesizers with classic oscillator waveforms, envelopes, filter, modulation and effects. The aim is to make it easy to create and modify sounds.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(lv2)
    - pkgconfig(sndfile)
setup      : |
    %configure --with-gui --with-alsa --with-jack --with-lv2 --with-vst
build      : |
    %make
install    : |
    %make_install
