name       : amsynth
version    : 1.12.4
release    : 15
source     :
    - https://github.com/amsynth/amsynth/releases/download/release-1.12.4/amsynth-1.12.4.tar.gz : 82209ea9c688e2403e7b09ecf53505647d9305fc90292c27893a976d49ef4bb9
homepage   : https://amsynth.github.io/
license    : GPL-2.0-only
component  : multimedia.audio
summary    : amsynth is an analog modelling software synthesizer
description: |
    amsynth is an analog modelling (a.k.a virtual analog) software synthesizer. It mimics the operation of early analog subtractive synthesizers with classic oscillator waveforms, envelopes, filter, modulation and effects. The aim is to make it easy to create and modify sounds.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(sndfile)
setup      : |
    %configure --with-jack
build      : |
    %make
install    : |
    %make_install
